### ISSUE TITLE
linux target platform

### ISSUE THREAD

**Issue by hkvaka** [BiologyTools/BioFormatsNET6#1]
Hi

I am looking at integrating the nuget package in to my solution .NET 6 running on a Linux target platform

I am getting the following error while installing the package, will this package work for Linux platform

![image](https://user-images.githubusercontent.com/118275347/221786982-75db6df0-d8e2-4f5b-81ed-987afc7827ff.png)

**Comment by BiologyTools** [comment]
I have just uploaded a revised version of the package updated with the latest Bioformats version as well as IKVM. When installing add the BioFormats.NET6 package and add IKVM 8.4.5. https://www.nuget.org/packages/BioFormats.NET6/6.12.0 Thank you for noticing this issue.

**Comment by hkvaka** [comment]
Thank you for quickly resolving this issue, I can now install both the packages as suggested.
could you please point me to any documentation/ code snippet how I can use the library, basically I wanted to generate deep zoom images for z stack whole slide images for .ndpi/svs/mrxs files

**Comment by BiologyTools** [comment]
The whole slide images I have used with BioGTK are opened by the BioImage.OpenOMETiled function. 'OpenOMETiled (string file, int serie, int tilex, int tiley, int tileSizeX, int tileSizeY)' https://biologytools.github.io/class_bio_g_t_k_1_1_bio_image.html However the images I have do not have Z-depth only multiple pyramidal resolutions. If the images open up correctly in BioGTK you should be able to use the open tile function I mentioned. Let me know what format your images are in?

**Comment by hkvaka** [comment]
Many Thanks for a quick reply

The image formats I am looking to process are ndpi, svs and mrxs. to start with I am looking to process a large ndpi file

**Comment by BiologyTools** [comment]
The files I have tested with were czi. But if they open up correctly with BioGTKApp. You should be able to use the "Crop" filter to get stacks from the whole slide image. You can use the Recorder to get code that should work in a script.

**Comment by hkvaka** [comment]
I've tried to create a new BioImage by passing the file path and getting no Information from the image object, is this the expected way to load an image, could you suggest how to load an image and get metadata
![image](https://user-images.githubusercontent.com/118275347/221811691-780952f3-e6cf-4abd-8bd3-377bb47adc15.png)

**Comment by BiologyTools** [comment]
The documentation needs to be updated I will be doing so today. Here is how to use the library to open part of an image.
App.Initialize();
//BioImage.OpenOME(string file, int series, bool openInNewTab, bool addToImages, bool tile, int tilex, int tiley, int tileSizeX, int tileSizeY)
//Note the series parameter is the pyramidal resolution for pyramidal images.
BioImage bi = BioImage.OpenOME("file", 0, false, true, 0,0,800,800);
BioImage.SaveOME("file to save to",bi.ID);

**Comment by hkvaka** [comment]
Thank you for the code snippet when I try to run the App.Initalize()  also tried BioImage..Initalize()  getting the below error

![image](https://user-images.githubusercontent.com/118275347/221821858-6a9fa171-7ddc-4211-a53a-5cf471bc1f38.png)

**Comment by BiologyTools** [comment]
It's throwing an error when trying to initialize the OME library using IKVM. Add a reference to the bioformats-package.dll which should be included in your project when you installed Bioformats.NET6.

**Comment by BiologyTools** [comment]
I noticed you are using Visual Studio Code for development I use Visual Studio 2022 Community for Windows. I'm not sure if you can get it to compile with Visual Studio Code.

**Comment by hkvaka** [comment]
I am using VS 2022 as well and noticed the bioformats-package.dll included in the proj files and marked it as always copy
I can see the dll being copied to the output directory but still get the above error
![image](https://user-images.githubusercontent.com/118275347/221828579-208ffe82-9b2c-47f1-a4cb-560c6364f5d9.png)

**Comment by BiologyTools** [comment]
![image](https://user-images.githubusercontent.com/84872500/221829790-d22490d8-dfde-495e-aa3a-2209ebdd1f41.png)
Is it showing up correctly in the Dependencies?

**Comment by hkvaka** [comment]
My dependencies look like this 
![image](https://user-images.githubusercontent.com/118275347/221831691-235e50ca-f721-425b-a913-a4d1db2ac411.png)

**Comment by BiologyTools** [comment]
Right click on dependencies and click "Add Project Reference..." then browse to the directory of your project and select the "bioformats_package.dll". Then you should have a assemblies reference like mine.

**Comment by hkvaka** [comment]
Thank you I've referenced it from the bin directory where its copied physically, not sure if thats what was suggested  and now get a different error
![image](https://user-images.githubusercontent.com/118275347/221843951-e1c47b1d-6389-4ebe-9816-f016f7376354.png)

**Comment by BiologyTools** [comment]
Hmm this is a GTK error which platform are you running on? You need to install GTK. https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows

**Comment by hkvaka** [comment]
my host OS is windows 10 target platform is Linux container running on  Docker

**Comment by BiologyTools** [comment]
Did you get it to work? I use windows for building and have tested BioGTK on Windows, Linux & Mac it should work. Let me know if I can help in any way? I have seen a similar message when running on Mac while GTK3 was not installed.

**Comment by hkvaka** [comment]
Thank you, unfortunately am stuck on that issue as part of the dependencies gtksharp has been already installed
![image](https://user-images.githubusercontent.com/118275347/221900046-c30c8e26-c43c-4327-ba8e-3bc672e10e9c.png)

**Comment by BiologyTools** [comment]
On Linux GTK3 comes with the operating system. While on Windows you need to install the GTK library as the link I provided instructs. https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows I use Glade on windows to make the GUI and glade works with GTK3 which is why I already have GTK3 installed.

**Comment by BiologyTools** [comment]
Looks like to run BioGTK on windows the package manager MSYS2 must be installed to install the package GTK3 and the path environmental variable must be updated as instructed. Without updating the path environmental variable the app will fail to initialize. https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows I will update the readme to include this information so it is more clear.

**Comment by BiologyTools** [comment]
Did you get BioGTK to work? You could also use "Bio" the WinForms version of the Library it also runs on Linux with Mono.

**Comment by hkvaka** [comment]
as my target platform is Linux did not install the windows Gtk. apologies, was side tracked with my other work, my main intention is to use the bio formats library in C# rather than using using java, can this library be used as a standalone package without any UI dependencies just as a back end processor,

**Comment by BiologyTools** [comment]
Yes it can be though it isn't the primary goal of the project, I have used it currently worked on viewing & ROI creation import & export as well as ImageJ integration. `BioImage.Initialize()` will initialize the Library alone. I am planning on making a headless mode like ImageJ has.

**Comment by BiologyTools** [comment]
I can make a non-gui version it won't take long should be done by tomorrow. If that's what you truly need.

**Comment by hkvaka** [comment]
Many thanks for your support, and all the efforts you are putting on the project.
It will be really helpful to have a wrapper library around bio-formats using C# that can be used to process z stack  whole slide images.

**Comment by BiologyTools** [comment]
I have uploaded a GUI-less version of the library. https://www.nuget.org/packages/BioLib/1.0.0 hopefully this will be more what you are looking for. Now just call BioImage.Initialize(); to initialize the OME library instead of App.Initialize();

**Comment by hkvaka** [comment]
Thankyou for quickly separating out the library, looks like its now missing the bioformat_package as I cant see that in the project 
![image](https://user-images.githubusercontent.com/118275347/222143623-e1442021-b3c0-41fa-98f6-41e14be9616e.png)

**Comment by BiologyTools** [comment]
I have updated the package https://www.nuget.org/packages/BioLib/1.2.0 and tested it with your use case here is the code I used. 
```
//The initial opening will take a while for large files due to Bioformats ImageReader setID method.
BioImage slide = BioImage.OpenOME(openFileDialog.FileName, 0, false, true, 0, 0, 800, 800);
//However opeing a tile from an already opened file is fast.
BioImage tile = BioImage.OpenOME(openFileDialog.FileName, 0, true, true, 20000, 20000, 800, 800);
BioImage.SaveOME(openFileDialog.FileName + ".ome.tif", tile.ID);
Images.RemoveImage(tile);
tile.Dispose();
```
I am sorry it took this long, but this worked for the images I have.

**Comment by BiologyTools** [comment]
Did you try out the code I provided? It does work with the images I have. I would like to solve this issue.

**Comment by hkvaka** [comment]
Thankyou for querying on this the original issue with related to missing package is solved ho ever noticing issues opening a file
and its taking long time to open the file this case I've only used a file of 100 mb ish, however I might end up with larger files around 15-20GB.
![image](https://user-images.githubusercontent.com/118275347/222678092-f42b6e03-53f8-41dd-818b-9e21053ecaa3.png)
![image](https://user-images.githubusercontent.com/118275347/222678140-2071a196-05d2-4fa6-be1c-f62b15f78545.png)

**Comment by hkvaka** [comment]
I've a java version of the bioformats code that picks the file so for time being I might stick with java, appreciate your help on this

**Comment by BiologyTools** [comment]
Performance wise there is not much I can do, it's caused by running Bioformats with IKVM. Bio uses Bitmiracle Libtiff to make it a bit faster to open non-whole-slide-images & saving stacks. To improve performance of whole slide images I would have to write a reader of my own in C#. If someone could provide me with more whole-slide-images to work with their support would be better. This is why I asked you if your images opened up ok in BioGTKApp.

**Comment by BiologyTools** [comment]
I have found now a better resource for whole-slide-images which include the formats you are using (ndpi, mrxs, and svs). I will be using these to improve whole-slide support. Thank you for considering my library.

**Comment by hkvaka** [comment]
Thankyou for all the support provided and also at a very quick pace, my best wishes for your project

**Comment by BiologyTools** [comment]
I have added support .ndpi whole slide images. The performance for .ndpi is actually much faster than the .czi files I had tried before. I love C# & with Glade the GUI is easy to make. Now people like me who don't know Java have something to work off of. Best wished for you as well.
